export const ADD_TODO_ITEM = "ADD_TODO_ITEM";
export const CROSS_TODO_ITEM = "CROSS_TODO_ITEM";
export const REMOVE_TODO_ITEM = "REMOVE_TODO_ITEM";
export const CLEAR_TODO_ITEMS = "CLEAR_TODO_ITEMS";
