export const ADD_TODO_ITEM = "ADD_TODO_ITEM";
export const CROSS_TODO_ITEM = "CROSS_TODO_ITEM";
export const REMOVE_TODO_ITEM = "REMOVE_TODO_ITEM";
export const CLEAR_COMPLETED_TODOS = "CLEAR_COMPLETED_TODOS";
export const CATEGORY_SELECTED = "CATEGORY_SELECTED";
